services:
  # Service MongoDB
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bezkoder_db
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend

  # Service Auth (Spring Boot)
  auth-service:
    build: ./backend/auth
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bezkoder_db
    depends_on:
      - mongodb
    networks:
      - backend

  # Service Road (Spring Boot)
  road-service:
    build: ./backend/road
    container_name: road-service
    ports:
      - "8081:8081"
    environment:
      - GRAPH_HOPPER_URL=http://graphhopper:8989
    # depends_on:
    #   - mongo
    networks:
      - backend

  # Service Frontend (React)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  mongo-data:
