name: CI/CD - Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-backend:
    strategy:
      matrix:
        name: [Java17]
        include:
          - name: Java17
            os: ubuntu-latest
            java-version: 17
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: Execute Maven Build for auth
        run: |
          cd auth
          mvn clean package -DskipTests

      - name: Execute Maven Build for road
        run: |
          cd road
          mvn clean package -DskipTests

      - name: Store Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: |
            auth/target/auth-0.0.1-SNAPSHOT.jar
            road/target/road-0.0.1-SNAPSHOT.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: tests-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for auth
        run: |
          cd auth
          docker build -t auth-service:latest -f Dockerfile .

      - name: Build Docker image for road
        run: |
          cd road
          docker build -t road-service:latest -f Dockerfile .
